# This is a basic workflow to help you get started with Actions

name: Deployment to surge

# Controls when the action will run. 
on:
  # Triggers the workflow on push or pull request events but only for the main branch
  push:
    branches: [ main ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2

      # Runs a single command using the runners shell
      - name: Node.js Installation
        uses: actions/setup-node@v2-beta
        with:
          version: 14.16.0

      # Runs a set of commands using the runners shell
      - name: Yarn Installation
        uses: borales/actions-yarn@2.0.0
        with:
          cmd: install
          
      - name: Build React App
        run: yarn build
        
      - name: Surge Isntallation
        run: npm install -g surge
        
      - name: Deployment to Surge
        run: surge ./build devday1.surge.sh --toekn ${{ secrets.surgeToken }}
